version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.3
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  dotnet-project: {}

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test-build-and-test-command:
    docker:
      - image: 'mcr.microsoft.com/dotnet/sdk:8.0'
    steps:
      - checkout

      - dotnet-project/build_and_test:
          project_solution: tests/Test.Service/Test.Service.sln          

  test-pack-and-push-docker-command:
    docker:
      - image: 'cimg/base:current'
    steps:
      - checkout

      - dotnet-project/pack_and_push_docker:
          dockerfile: "tests/Test.Service/src/Test.Service.Api/Dockerfile"
          docker_context: "tests/Test.Service"
          image_name: test-service
          image_tag: "v1.0.0"

  test-pack-and-push-helm-command:
    docker:
      - image: 'cimg/base:current'
    steps:
      - checkout

      - dotnet-project/pack_and_push_helm:
          helm_repo: "youtilitycr.azurecr.io/helm/alpha"
          helm_chart_name: "test-service"
          helm_chart_version: "v1.0.0"

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
      - test-build-and-test-command:
          filters: *filters
      - test-pack-and-push-docker-command:
          requires:
            - test-build-and-test-command
          filters: *filters
      - test-pack-and-push-helm-command:
          requires:
            - test-pack-and-push-docker-command
          filters: *filters
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: mt-lab/dotnet-project
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - test-build-and-test-command
            - test-pack-and-push-docker-command
            - test-pack-and-push-helm-command
          context: orb-publishing
          filters: *release-filters
